<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use \App\Models\permohonan;

class PermohonanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permohonans = [
            [
                'user_id' => 9,
                'id_pendaftaran' => 'sp20250410001',
                'alamat_jalan' => 'Jl. Semarak 01',
                'alamat_kelurahan' => 'Padang Serai',
                'alamat_kecamatan' => 'Kampung Melayu',
                'lokasi_jalan' => 'Jl. Semarak Rt.05 RW.02',
                'lokasi_kelurahan' => 'Padang Serai',
                'lokasi_kecamatan' => 'Kampung Melayu',
                'luas_lahan' => '225',
                'penggunaan' => 'Tanah Perkebunan',
                'kepemilikan' => 'Hak Milik (SHM)',
                'status' => 'diterima',
                'no_surat' => '1803173913',
                'file_surat' => 'surat/permohonan1.pdf',
                'tanggal_masuk' => '2025-04-10',
            ],
            [
                'user_id' => 10,
                'id_pendaftaran' => 'sp20250115001',
                'alamat_jalan' => 'Jl. Merdeka No.10',
                'alamat_kelurahan' => 'Lingkar Timur',
                'alamat_kecamatan' => 'Gading Cempaka',
                'lokasi_jalan' => 'Jl. Merdeka RT.01 RW.01',
                'lokasi_kelurahan' => 'Lingkar Timur',
                'lokasi_kecamatan' => 'Gading Cempaka',
                'luas_lahan' => '150',
                'penggunaan' => 'Rumah Tinggal',
                'kepemilikan' => 'Hak Guna Bangunan (HGB)',
                'status' => 'diterima',
                'no_surat' => '2025011501',
                'file_surat' => 'surat/permohonan1.pdf',
                'tanggal_masuk' => '2025-01-15',
            ],
            [
                'user_id' => 11,
                'id_pendaftaran' => 'sp20250205002',
                'alamat_jalan' => 'Jl. Veteran No.23',
                'alamat_kelurahan' => 'Bentiring',
                'alamat_kecamatan' => 'Muara Bangka Hulu',
                'lokasi_jalan' => 'Jl. Veteran RT.02 RW.01',
                'lokasi_kelurahan' => 'Bentiring',
                'lokasi_kecamatan' => 'Muara Bangka Hulu',
                'luas_lahan' => '300',
                'penggunaan' => 'Tanah Kosong',
                'kepemilikan' => 'Hak Guna Usaha (HGU)',
                'status' => 'diterima',
                'no_surat' => '2025020502',
                'file_surat' => 'surat/permohonan2.pdf',
                'tanggal_masuk' => '2025-02-05',
            ],
            [
                'user_id' => 12,
                'id_pendaftaran' => 'sp20250312003',
                'alamat_jalan' => 'Jl. Cempaka No.45',
                'alamat_kelurahan' => 'Pematang Gubernur',
                'alamat_kecamatan' => 'Muara Bangka Hulu',
                'lokasi_jalan' => 'Jl. Cempaka RT.03 RW.02',
                'lokasi_kelurahan' => 'Pematang Gubernur',
                'lokasi_kecamatan' => 'Muara Bangka Hulu',
                'luas_lahan' => '200',
                'penggunaan' => 'Gudang',
                'kepemilikan' => 'Hak Pakai',
                'status' => 'diterima',
                'no_surat' => '2025031203',
                'file_surat' => 'surat/permohonan3.pdf',
                'tanggal_masuk' => '2025-03-12',
            ],
            [
                'user_id' => 13,
                'id_pendaftaran' => 'sp20250410004',
                'alamat_jalan' => 'Jl. Semarak 01',
                'alamat_kelurahan' => 'Padang Serai',
                'alamat_kecamatan' => 'Kampung Melayu',
                'lokasi_jalan' => 'Jl. Semarak Rt.05 RW.02',
                'lokasi_kelurahan' => 'Padang Serai',
                'lokasi_kecamatan' => 'Kampung Melayu',
                'luas_lahan' => '225',
                'penggunaan' => 'Tanah Perkebunan',
                'kepemilikan' => 'Hak Milik (SHM)',
                'status' => 'diterima',
                'no_surat' => '2025041004',
                'file_surat' => 'surat/permohonan4.pdf',
                'tanggal_masuk' => '2025-04-10',
            ],
            [
                'user_id' => 14,
                'id_pendaftaran' => 'sp20250421005',
                'alamat_jalan' => 'Jl. Raya Timur No.7',
                'alamat_kelurahan' => 'Surabaya',
                'alamat_kecamatan' => 'Sungai Serut',
                'lokasi_jalan' => 'Jl. Raya Timur RT.01 RW.03',
                'lokasi_kelurahan' => 'Surabaya',
                'lokasi_kecamatan' => 'Sungai Serut',
                'luas_lahan' => '180',
                'penggunaan' => 'Warung',
                'kepemilikan' => 'Hak Guna Bangunan (HGB)',
                'status' => 'diterima',
                'no_surat' => '2025042105',
                'file_surat' => 'surat/permohonan5.pdf',
                'tanggal_masuk' => '2025-04-21',
            ],
            [
                'user_id' => 15,
                'id_pendaftaran' => 'sp20250502006',
                'alamat_jalan' => 'Jl. Tanjung Agung No.5',
                'alamat_kelurahan' => 'Tanjung Agung',
                'alamat_kecamatan' => 'Sungai Serut',
                'lokasi_jalan' => 'Jl. Tanjung Agung RT.03 RW.04',
                'lokasi_kelurahan' => 'Tanjung Agung',
                'lokasi_kecamatan' => 'Sungai Serut',
                'luas_lahan' => '240',
                'penggunaan' => 'Peternakan',
                'kepemilikan' => 'Hak Guna Usaha (HGU)',
                'status' => 'diterima',
                'no_surat' => '2025050206',
                'file_surat' => 'surat/permohonan6.pdf',
                'tanggal_masuk' => '2025-05-02',
            ],
            [
                'user_id' => 16,
                'id_pendaftaran' => 'sp20250503007',
                'alamat_jalan' => 'Jl. Gajah Mada No.99',
                'alamat_kelurahan' => 'Anggut Atas',
                'alamat_kecamatan' => 'Ratu Samban',
                'lokasi_jalan' => 'Jl. Gajah Mada RT.02 RW.02',
                'lokasi_kelurahan' => 'Anggut Atas',
                'lokasi_kecamatan' => 'Ratu Samban',
                'luas_lahan' => '170',
                'penggunaan' => 'Kebun Sayur',
                'kepemilikan' => 'Hak Pakai',
                'status' => 'diterima',
                'no_surat' => '2025050307',
                'file_surat' => 'surat/permohonan7.pdf',
                'tanggal_masuk' => '2025-05-03',
            ],
            [
                'user_id' => 17,
                'id_pendaftaran' => 'sp20250601008',
                'alamat_jalan' => 'Jl. Seruni No.11',
                'alamat_kelurahan' => 'Kandang Mas',
                'alamat_kecamatan' => 'Kampung Melayu',
                'lokasi_jalan' => 'Jl. Seruni RT.04 RW.03',
                'lokasi_kelurahan' => 'Kandang Mas',
                'lokasi_kecamatan' => 'Kampung Melayu',
                'luas_lahan' => '260',
                'penggunaan' => 'Lahan Kosong',
                'kepemilikan' => 'Hak Milik (SHM)',
                'status' => 'diterima',
                'no_surat' => '2025060108',
                'file_surat' => 'surat/permohonan8.pdf',
                'tanggal_masuk' => '2025-02-01',
            ],
            [
                'user_id' => 18,
                'id_pendaftaran' => 'sp20250615009',
                'alamat_jalan' => 'Jl. Mawar No.2',
                'alamat_kelurahan' => 'Dusun Baru',
                'alamat_kecamatan' => 'Sungai Serut',
                'lokasi_jalan' => 'Jl. Mawar RT.05 RW.04',
                'lokasi_kelurahan' => 'Dusun Baru',
                'lokasi_kecamatan' => 'Sungai Serut',
                'luas_lahan' => '190',
                'penggunaan' => 'Toko',
                'kepemilikan' => 'Hak Guna Bangunan (HGB)',
                'status' => 'diterima',
                'no_surat' => '2025061509',
                'file_surat' => 'surat/permohonan9.pdf',
                'tanggal_masuk' => '2025-02-15',
            ],
            [
                'user_id' => 19,
                'id_pendaftaran' => 'sp20250701010',
                'alamat_jalan' => 'Jl. Satria No.1',
                'alamat_kelurahan' => 'Pasar Melintang',
                'alamat_kecamatan' => 'Ratu Samban',
                'lokasi_jalan' => 'Jl. Satria RT.03 RW.01',
                'lokasi_kelurahan' => 'Pasar Melintang',
                'lokasi_kecamatan' => 'Ratu Samban',
                'luas_lahan' => '210',
                'penggunaan' => 'Rumah Tinggal',
                'kepemilikan' => 'Hak Pakai',
                'status' => 'diterima',
                'no_surat' => '2025070110',
                'file_surat' => 'surat/permohonan10.pdf',
                'tanggal_masuk' => '2025-02-01',
            ],
        ];

        foreach ($permohonans as $permohonan) {
            Permohonan::create($permohonan);
        }
    }
}
